name: Alpha Release

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  push:
    branches: [alpha]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # install yarn
      - name: Install yarn
        run: npm i -g yarn

      # Install package dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Build
        run: yarn build

  alpha-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dsfx3d'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Release
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
